version: '3.8'

services:
  admin:
    build: ./admin
    volumes:
      - ./admin:/app
    ports:
      - "8002:8002"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.django.rule=Host(`admin-app.traefik.me`)"
      - "traefik.http.routers.django.entrypoints=web"


  user:
    build: ./user
    volumes:
      - ./user:/app
    ports:
      - "8001:8001"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.django.rule=Host(`user.traefik.me`)"
      - "traefik.http.routers.django.entrypoints=web"


  traefik:
    image: traefik:v2.2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./traefik.toml:/etc/traefik/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock"